### ISSUE TITLE
Remove unknown trophies

### ISSUE THREAD

**Issue by kastney** [kastney/kastney#6]
## Tasks

- [x] Remove trophies with missing or unknown values ​​like "Reviews"
- [x] Remove Jointed trophy
- [x] Replace trophy theme to more intuitive colors
